fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

api:
    type: rest
    resource: "routing_api.yml"
    prefix:   /api

crm:
    resource: "@CRMBundle/Resources/config/routing.yml"
    prefix:   /crm

crm_homepage:
    path:     /
    defaults: { _controller: "CRMBundle:Default:index" }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"