api_hire:
  type: rest
  resource: ApiBundle\Controller\HireController
  prefix:   /v1

api_car:
  type: rest
  resource: ApiBundle\Controller\CarController
  prefix:   /v1

api_customer:
  type: rest
  resource: ApiBundle\Controller\CustomerController
  prefix:   /v1

api_mark:
  type: rest
  resource: ApiBundle\Controller\MarkController
  prefix:   /v1

api_point:
  type: rest
  resource: ApiBundle\Controller\PointController
  prefix:   /v1

api_post:
  type: rest
  resource: ApiBundle\Controller\PostController
  prefix:   /v1

api_worker:
  type: rest
  resource: ApiBundle\Controller\WorkerController
  prefix:   /v1
