point_index:
    path:     /
    defaults: { _controller: "AppBundle:Point:index" }
    methods:  GET

point_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Point:show" }
    methods:  GET

point_new:
    path:     /new
    defaults: { _controller: "AppBundle:Point:new" }
    methods:  [GET, POST]

point_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Point:edit" }
    methods:  [GET, POST]

point_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Point:delete" }
    methods:  DELETE
