rate_index:
    path:     /
    defaults: { _controller: "AppBundle:Rate:index" }
    methods:  GET

rate_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Rate:show" }
    methods:  GET

rate_new:
    path:     /new
    defaults: { _controller: "AppBundle:Rate:new" }
    methods:  [GET, POST]

rate_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Rate:edit" }
    methods:  [GET, POST]

rate_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Rate:delete" }
    methods:  DELETE
