worker_index:
    path:     /
    defaults: { _controller: "CRMBundle:Worker:index" }
    methods:  GET

worker_show:
    path:     /{id}/show
    defaults: { _controller: "CRMBundle:Worker:show" }
    methods:  GET

worker_new:
    path:     /new
    defaults: { _controller: "CRMBundle:Worker:new" }
    methods:  [GET, POST]

worker_edit:
    path:     /{id}/edit
    defaults: { _controller: "CRMBundle:Worker:edit" }
    methods:  [GET, POST]

worker_delete:
    path:     /{id}/delete
    defaults: { _controller: "CRMBundle:Worker:delete" }
    methods:  DELETE
